Add missing 'typing' module for django-extensions
I found this error when running `make`.

django_extensions/admin/__init__.py", line 9, in <module>
    from typing import Tuple, Dict, Callable  # NOQA
    ImportError: No module named typing